.TH "TLA2VCD" "1" "1.0" "Emil" "Tektronix File Format Conversion"
.SH "NAME"
.LP 
tla2vcd \- Converts TLA to VCD or LST files
.SH "SYNTAX"
.LP 
tla2vcd [\fIoption\fP]... \fITLAFILE\fP [[\fITLAFILE\fP]...]

.SH "DESCRIPTION"
.LP 
Converts TLA files from Tektronix logic analyzers to VCD or LST files.  Conversion to VCD allows viewing in tools such as  \fIgtkwave\fP(1).
.SH "OPTIONS"
.LP 
.TP 

\fB\-t\fR
Generate text LST file instead of VCD file
.TP
\fB\-l\fR
List the available channels/groups and exit
.TP
\fB\-s\fR  <\fIsignal_list\fP>
Select signals from regular expression list
.TP
\fB\-a\fR
All channels
.TP
\fB\-m\fR
Append MagniVu info (only in listing mode)
.TP
\fB\-z\fR
Compress output
.TP
\fB\-v\fR
Verbose

.SH "AUTHORS"
.LP 
Emil
.SH "SEE ALSO"
.LP 
\fIlxt2vcd\fP(1) \fIvzt2vcd\fP(1) \fIgtkwave\fP(1)
