#!/bin/sh

cd src

if [ `uname` = "Linux" ]
	then
	LFSC=`grep "_LARGEFILE_SOURCE 1" ../config.h|wc -l`
	if [ "$LFSC" -ne "0" ]
		then
		echo "Linux detected, configuring makefiles for 64-bit fileio support..."
		for BIGF in Makefile libz/Makefile libbz2/Makefile helpers/Makefile ;
			do
			cat $BIGF | sed 's/\(^CFLAGS =.*$\)/\1 $(BIGFILES)/' >$BIGF.tmp
			mv $BIGF.tmp $BIGF
			done
		fi
	fi

if [ `uname` = "AIX" ]
	then
	echo "AIX detected, configuring for > 256MB memory usage..."
	cat Makefile | sed 's/\(^CFLAGS =.*$\)/\1 $(AIXFLAGS)/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cd helpers
	cat Makefile | sed 's/\(^CFLAGS =.*$\)/\1 $(AIXFLAGS)/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cd ..
	fi

HRPC=`grep "HAVE_LIBRPC 1" ../config.h|wc -l`
if [ "$HRPC" -ne "0" ]
        then
	echo "librpc found, configuring makefiles..."
	cat Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lrpc/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cat helpers/Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lrpc/' >helpers/Makefile.tmp
	mv helpers/Makefile.tmp helpers/Makefile
	cat ../contrib/rtlbrowse/Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lrpc/' >../contrib/rtlbrowse/Makefile.tmp
	mv ../contrib/rtlbrowse/Makefile.tmp ../contrib/rtlbrowse/Makefile
	fi

HNSL=`grep "HAVE_LIBNSL 1" ../config.h|wc -l`
if [ "$HNSL" -ne "0" ]
        then
	echo "libnsl found, configuring makefiles..."
	cat Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lnsl/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cat helpers/Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lnsl/' >helpers/Makefile.tmp
	mv helpers/Makefile.tmp helpers/Makefile
	cat ../contrib/rtlbrowse/Makefile | sed 's/^NSLLIB =.*$/NSLLIB = -lnsl/' >../contrib/rtlbrowse/Makefile.tmp
	mv ../contrib/rtlbrowse/Makefile.tmp ../contrib/rtlbrowse/Makefile
	fi

HPTH=`grep "HAVE_LIBPTHREAD 1" ../config.h|wc -l`
if [ "$HPTH" -ne "0" ]
        then
	echo "libpthread found, configuring makefiles..."
	cat Makefile | sed 's/^PTHLIB =.*$/PTHLIB = -lpthread/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cat helpers/Makefile | sed 's/^PTHLIB =.*$/PTHLIB = -lpthread/' >helpers/Makefile.tmp
	mv helpers/Makefile.tmp helpers/Makefile
	cat ../contrib/rtlbrowse/Makefile | sed 's/^PTHLIB =.*$/PTHLIB = -lpthread/' >../contrib/rtlbrowse/Makefile.tmp
	mv ../contrib/rtlbrowse/Makefile.tmp ../contrib/rtlbrowse/Makefile
	fi

#
# if you don't know what ae2 is, you shouldn't be using it, sorry...
#
for AETLIB in /afs/awd/projects/simarama/releases/latest/libae2rw.a /afs/awd/projects/simarama/releases/latest/libae2rw.so;
do
if [ -e $AETLIB ]
	then
	echo "AET2 library found at "$AETLIB", configuring for use..."
	cat Makefile | sed 's/\(^CFLAGS =.*$\)/\1 -DAET2_IS_PRESENT/' | sed "s#AET2LIB =#AET2LIB = $AETLIB#" | sed 's#\(^LIBS =.*$\)#\1 \$\(AET2LIB\)#' >Makefile.tmp
	mv Makefile.tmp Makefile
	fi
done

cd ../contrib/rtlbrowse

if [ `uname` = "Linux" ]
	then
	if [ "$LFSC" -ne "0" ]
		then
		echo "Linux detected, configuring makefiles for 64-bit fileio support..."
		for BIGF in Makefile ;
			do
			cat $BIGF | sed 's/\(^CFLAGS =.*$\)/\1 $(BIGFILES)/' >$BIGF.tmp
			mv $BIGF.tmp $BIGF
			done
		fi
	fi

if [ `uname` = "AIX" ]
	then
	echo "AIX detected, configuring for > 256MB memory usage..."
	cat Makefile | sed 's/\(^CFLAGS =.*$\)/\1 $(AIXFLAGS)/' >Makefile.tmp
	mv Makefile.tmp Makefile
# patch possible colon substitution in AIX...
	cat Makefile | sed 's/^LEX = :/LEX = flex/' >Makefile.tmp
	mv Makefile.tmp Makefile
	fi

if [ `uname` = "FreeBSD" ]
	then
	echo "FreeBSD detected, configuring for thread usage (currently disabled)..."
	cat Makefile | sed 's/^PTHLIB =.*$/PTHLIB = /' >Makefile.tmp
	mv Makefile.tmp Makefile
	cat helpers/Makefile | sed 's/-lpthread//' >helpers/Makefile.tmp
	mv helpers/Makefile.tmp helpers/Makefile
	fi

#
# if you don't know what ae2 is, you shouldn't be using it, sorry...
#
for AETLIB in /afs/awd/projects/simarama/releases/latest/libae2rw.a /afs/awd/projects/simarama/releases/latest/libae2rw.so;
do
if [ -e $AETLIB ]
	then
	echo "AET2 library found at "$AETLIB", configuring for use..."
	cat Makefile | sed 's/\(^CFLAGS =.*$\)/\1 -DAET2_IS_PRESENT/' | sed "s#AET2LIB =#AET2LIB = $AETLIB#" | sed 's#\(^LIBS =.*$\)#\1 \$\(AET2LIB\)#' >Makefile.tmp
	mv Makefile.tmp Makefile
	fi
done

cd ../../

if [ `uname` = "AIX" ]
	then
	echo "AIX detected, patching cc to gcc in Makefile for pccts and vermin compiles..."
	cd contrib/pccts
	cat Makefile | sed 's/^CC=cc/CC=gcc/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cd ../../
	cd contrib/vermin
	cat Makefile | sed 's/^CC=cc/CC=gcc/' >Makefile.tmp
	mv Makefile.tmp Makefile
	cd ../../
	fi
