.TH "MVL2LXT" "1" "1.3.34" "Anthony Bybell" "Filetype Conversion"
.SH "NAME"
.LP 
mvl2lxt \- Coverts MVLSIM AET files to LXT
.SH "SYNTAX"
.LP 
mvl2lxt <\fIfilename.aet\fP> <\fIfilename.lxt\fP>
.SH "DESCRIPTION"
.LP 
Converts AET files to LXT.  This is experimental as it is not a complete implementation and is not intended for general use.
.SH "AUTHORS"
.LP 
Anthony Bybell <bybell@nc.rr.com>
.SH "SEE ALSO"
.LP 
\fItex2vcd\fP(1) \fImvl2vcd\fP(1) \fIlxt2vcd\fP(1) \fIvcd2lxt2\fP(1) \fIvcd2lxt\fP(1) \fIgtkwave\fP(1)
