/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $NetBSD: flex.skl,v 1.20 2004/02/01 21:24:02 christos Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, yy_size_t len ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ))
#ifdef __GNUC__
    __attribute__((__unused__))
#endif
;
static void yy_flex_free YY_PROTO(( void * ));

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 126
#define YY_END_OF_BUFFER 127
static yyconst short int yy_accept[449] =
    {   0,
        0,    0,    0,    0,    0,    0,  127,  125,  121,  122,
      125,  125,  125,  125,  125,  125,  115,  112,  125,  125,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
        4,    6,    5,    5,    5,  107,  108,  121,    0,  124,
      111,    0,    0,    0,    0,  120,  114,    1,  123,  115,
      112,    0,  110,  109,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
       33,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,   48,  112,  112,  112,  112,  112,  112,  112,  112,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,    4,
        3,    2,  107,  111,    0,  117,    0,  116,    0,  119,
        0,  118,  114,  123,  113,  109,  112,    8,  112,  112,
       11,  112,  112,  112,  112,  112,  112,  112,   24,  112,
       27,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,  112,  112,   44,   45,  112,  112,  112,
      112,  112,  112,  112,  112,   59,  112,  112,  112,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
       78,  112,  112,  112,  112,  112,  112,   91,  112,   93,

      117,  116,  119,  118,  113,  112,  112,  112,  112,   14,
       17,  112,  112,  112,  112,   22,   23,  112,  112,  112,
      112,  112,  112,  112,  112,  112,   30,  112,  112,  112,
      112,  112,  112,   38,  112,  112,  112,  112,   41,  112,
       43,  112,  112,  112,   51,  112,  112,  112,  112,   58,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,   94,   74,   75,   79,   80,  112,  112,  112,  112,
       85,   86,  112,  112,   90,   92,  112,  112,   10,  112,
       15,   16,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,   26,   28,  112,  112,  112,  112,   35,   36,

      112,   39,  112,  112,  112,  112,  112,  112,  112,  112,
      112,   53,   54,  112,  112,   57,  112,  112,   62,   63,
       64,  112,   68,  112,  112,  112,  112,   98,  112,  112,
       82,  112,  112,   87,   88,   89,    7,    9,   12,   13,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  112,   31,   32,  112,  112,  112,   40,  103,
      112,   46,   47,   49,  112,  112,  112,  112,   56,  112,
       61,  112,  112,  112,  112,  112,  112,  112,   81,   83,
      112,  112,   19,  112,   21,   25,  112,  112,  112,  112,
      112,   95,   29,  112,   34,   37,  112,   42,  112,   52,

      112,  112,   60,  112,  112,  100,  112,   70,   71,   72,
       73,   76,   77,  112,   18,   20,  112,  112,  112,  112,
       99,   96,  112,  112,  112,   55,   65,   66,   67,  112,
       84,  112,  105,  112,  112,  112,   50,  104,   69,  112,
      112,  101,  112,   97,  112,  102,  106,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    1,    6,    1,    1,    7,    1,
        1,    8,    1,    1,    1,    9,   10,   11,   12,   13,
       13,   13,   13,   13,   13,   14,   14,    1,    1,    1,
        1,    1,   15,    1,   16,   17,   16,   18,   16,   16,
       19,   20,   19,   19,   19,   19,   19,   19,   21,   19,
       19,   19,   19,   19,   19,   19,   19,   22,   19,   22,
        1,   23,    1,    1,   24,   25,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   35,   36,   37,   38,   39,
       40,   41,   19,   42,   43,   44,   45,   46,   47,   48,
       49,   50,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[51] =
    {   0,
        1,    2,    3,    4,    1,    5,    1,    6,    7,    6,
        8,    8,    8,    8,    1,    9,    9,    9,   10,   10,
       10,    9,    6,   11,    1,    9,    9,    9,    9,    9,
        9,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,    9,   10,    9
    } ;

static yyconst short int yy_base[467] =
    {   0,
        0,    0,   48,   49, 1022, 1021, 1023, 1026,   51, 1026,
     1017,    0,   56, 1011,    0,   52,   52, 1011,    0,    0,
       45,   60,   61,   70,   69,   52,   59,   71,   72,   77,
       92,   98,   85,  105,  107,  111,  100,  110,  132,  114,
        0, 1026, 1009, 1010, 1026,    0, 1026,  109, 1012, 1026,
        0,  158,  165, 1014,  172, 1026,    0, 1026,    0,  175,
     1006,    0,    0,    0,   82,   66,  116,  112,  159,  148,
      124,  166,  152,  172,  162,  173,  184,  154,  189,  191,
     1005,  190,  192,  194,  201,  198,  203,  200,  206,  202,
      204, 1004,  207,  208,  209,  210,  224,  226,  216,  234,

      231,  232,  235,  236,  238,  243,  246,  248,  247,  256,
      250,  252,  258,  259,  269,  263,  270,  273,  272,    0,
     1026, 1026,    0,    0,  284,  296,  313,  317, 1010,    0,
      336,  339,    0,    0, 1002,    0,  274, 1001,  282,  289,
      301,  292,  278,  293,  328,  330,  310,  334,  350,  333,
      346,  351,  284,  324,  300,  353,  362,  344,  348,  357,
      356,  358,  366,  376,  361, 1000,  368,  364,  387,  388,
      391,  392,  398,  399,  400,  999,  402,  403,  401,  405,
      408,  406,  407,  410,  409,  411,  413,  415,  416,  414,
      445,  417,  418,  419,  427,  431,  446,  998,  433,  997,

      455,  469,    0,  477,  996,  420,  463,  455,  465,  450,
      995,  449,  464,  482,  438,  994,  993,  488,  475,  477,
      469,  493,  495,  497,  498,  501,  992,  504,  503,  506,
      507,  510,  513,  991,  509,  515,  514,  520,  990,  517,
      989,  521,  522,  523,  988,  527,  524,  551,  526,  987,
      540,  555,  528,  529,  534,  556,  533,  559,  535,  541,
      567,  986,  985,  568,  984,  983,  566,  570,  574,  575,
      982,  981,  576,  577,  980,  979,  580,  581,  978,  583,
      977,  976,  582,  589,  590,  592,  594,  597,  599,  600,
      601,  608,  975,  974,  609,  604,  610,  615,  973,  972,

      616,  971,  602,  605,  618,  621,  633,  624,  640,  641,
      638,  970,  969,  643,  645,  968,  646,  647,  967,  966,
      650,  648,  965,  649,  651,  653,  652,  964,  656,  663,
      963,  662,  654,  962,  956,  953,  946,  945,  932,  925,
      665,  655,  667,  658,  670,  686,  657,  660,  694,  669,
      672,  695,  696,  924,  920,  698,  700,  701,  919,  918,
      702,  917,  916,  910,  703,  704,  706,  707,  909,  708,
      899,  712,  709,  710,  711,  714,  718,  737,  891,  888,
      715,  719,  875,  722,  874,  873,  724,  735,  741,  742,
      743,  866,  851,  746,  850,  824,  748,  823,  752,  822,

      747,  753,  820,  754,  755,  819,  760,  818,  817,  814,
      811,  809,  808,  758,  807,  802,  761,  769,  762,  765,
      801,  800,  770,  771,  772,  799,  798,  796,  792,  774,
      791,  779,  789,  780,  781,  785,  666,  451,  295,  782,
      788,  228,  794,  212,  795,  108,   58, 1026,  834,  845,
      856,  859,  862,  869,  880,  883,  894,  905,  912,  922,
      927,  938,  941,  948,  952,  959
    } ;

static yyconst short int yy_def[467] =
    {   0,
      448,    1,  449,  449,  450,  450,  448,  448,  448,  448,
      451,  452,  448,  448,  453,  448,  448,  454,  455,  456,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      457,  448,  448,  448,  448,  458,  448,  448,  451,  448,
      459,  448,  448,  460,  448,  448,  461,  448,  462,  448,
      454,  463,  455,  464,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  457,
      448,  448,  458,  459,  448,  448,  448,  448,  460,  465,
      448,  448,  461,  462,  466,  464,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      448,  448,  465,  448,  466,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,

      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,  454,  454,  454,
      454,  454,  454,  454,  454,  454,  454,    0,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448
    } ;

static yyconst short int yy_nxt[1077] =
    {   0,
        8,    9,   10,    9,   11,   12,   13,   14,   15,   16,
       17,   17,   17,   17,    8,   18,   18,   18,   18,   18,
       18,   18,   19,   18,   20,   21,   22,   23,   24,   25,
       26,   18,   27,   28,   29,   18,   30,   31,   32,   33,
       34,   35,   36,   37,   18,   38,   39,   40,   18,   18,
       42,   42,   48,   62,   48,   43,   43,   44,   44,   58,
       62,   59,   60,   60,   60,   60,   62,   62,   62,   62,
       45,   45,   52,   53,   62,   54,   55,   62,   62,   62,
       62,   65,   52,   66,   53,   62,   70,   67,   54,   68,
       62,   78,   80,   62,  138,   55,   79,   74,   71,   72,

       62,   81,   84,   73,   69,   75,   62,   76,   62,   82,
       48,   83,   48,   62,   77,   62,   62,   85,   62,   62,
       62,   86,   62,   88,   62,  109,   92,   89,  137,   93,
       94,   87,   62,  110,   99,   90,  100,   91,  104,  112,
       62,  111,   95,  140,   96,  101,   97,  102,  105,   98,
      103,  106,  118,  119,  107,  108,   62,  113,  139,  125,
       62,  114,   62,  143,  115,  116,  127,   62,  126,  126,
       62,  117,  126,  131,   62,  128,  128,  128,  128,  126,
       62,   62,  132,  132,  132,   60,   60,   60,   60,  141,
      142,  144,   62,  132,  146,  151,  145,   62,   62,   62,

       62,  149,   62,  147,  148,  126,   62,  126,   62,   62,
       62,   62,   62,  150,   62,   62,   62,   62,   62,  132,
       62,  132,  153,  154,   62,  158,  161,  152,  160,  155,
      156,  162,   62,  157,   62,  159,   62,  164,  163,   62,
       62,  165,   62,   62,   62,  166,   62,  167,  170,  169,
      168,   62,  171,  174,   62,   62,   62,  172,   62,  175,
       62,  182,  173,  183,   62,  176,   62,   62,  179,  180,
      177,   62,  184,  187,  178,  190,  181,   62,   62,  192,
       62,   62,   62,  191,  195,  125,   62,  185,  186,  188,
       62,  193,   62,  189,  126,  126,  194,   62,  126,  206,

       62,   62,  196,   62,  197,  126,  201,  201,   62,   62,
      201,  198,  199,  200,  127,  207,  229,  201,   62,  201,
      211,  210,  208,  128,  128,  128,  128,  202,  202,  202,
      202,  126,   62,  126,  209,  212,   62,  131,   62,  216,
      202,   62,   62,  201,  231,  201,  132,  132,  132,  204,
      204,  204,   62,  213,   62,  215,   62,  132,   62,   62,
      204,   62,  204,  217,   62,   62,   62,  230,  214,   62,
       62,  224,   62,  225,   62,  226,   62,  218,  228,  235,
      219,  227,  234,  132,   62,  132,  204,  220,  204,  237,
      221,  233,  222,  223,  239,   62,   62,  232,  236,   62,

       62,  242,  238,  241,  243,  240,   62,   62,   62,   62,
       62,   62,  244,   62,   62,   62,   62,   62,   62,   62,
      246,   62,   62,   62,   62,   62,   62,   62,   62,  247,
      245,  251,  252,  255,  248,   62,  250,  258,  249,   62,
      253,   62,  256,  257,  254,  263,   62,  272,  259,  261,
      262,  260,  264,   62,   62,  265,  266,   62,   62,   62,
      270,  271,  273,   62,  286,  201,  201,  274,  277,  201,
      267,   62,   62,   62,  276,  275,  201,   62,  201,  202,
      202,  202,  202,   62,  268,   62,  269,  204,  204,  204,
       62,  283,  202,  279,  278,  280,   62,  281,  204,  282,

      204,   62,  201,   62,  201,   62,   62,  285,  284,   62,
      290,   62,   62,  287,   62,   62,  289,   62,   62,  288,
      292,   62,   62,   62,  204,   62,  204,  294,   62,   62,
       62,   62,   62,  291,   62,   62,   62,   62,  302,  298,
      293,   62,   62,   62,  301,  306,  295,  296,   62,   62,
      299,  307,  297,  300,  303,  310,  305,  311,  304,   62,
      309,  312,  313,   62,   62,  317,  308,   62,  316,  323,
      319,  320,  321,  326,   62,   62,   62,  327,   62,  314,
      318,  322,   62,   62,   62,   62,  334,  335,   62,   62,
       62,   62,  324,  339,  340,  315,  328,   62,   62,  325,

       62,  329,   62,  332,  330,   62,  336,   62,   62,   62,
       62,  331,   62,   62,  333,  341,   62,   62,   62,  338,
      354,  355,  337,   62,   62,  342,   62,  347,  344,   62,
      349,  343,   62,  348,  350,  346,  345,  353,  352,  358,
      356,   62,  359,  362,  363,  357,   62,  360,   62,   62,
      351,   62,  361,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,  364,   62,  365,
       62,   62,  366,   62,   62,   62,  375,   62,   62,  374,
       62,  367,  368,  372,  376,  369,  378,  385,  370,  373,
      371,  379,  384,  380,   62,  381,  382,  389,  383,  386,

      377,  388,   62,   62,   62,  391,   62,  392,   62,   62,
       62,   62,   62,  387,   62,   62,   62,   62,   62,   62,
       62,  390,   62,   62,  408,  409,   62,   62,  410,  411,
       62,  398,   62,  400,  395,  394,  393,  403,  405,  401,
      397,  396,  404,   62,  414,   62,  399,  412,  413,   62,
       62,   62,  407,  402,   62,   62,   62,  415,  406,  416,
       62,   62,   62,   62,  427,  428,   62,  417,   62,   62,
       62,  418,  421,   62,  419,  420,  423,   62,   62,   62,
       62,  424,   62,  429,  422,  430,  431,   62,   62,   62,
       62,  426,  425,   62,  432,  435,   62,   62,  433,   62,

       62,  438,   62,   62,   62,  434,   62,   62,   62,   62,
       62,  439,  437,  441,  436,   62,   62,   62,  440,   62,
      444,  443,   62,  446,  447,   62,   62,   62,   62,  442,
       62,   62,   62,  445,   41,   41,   41,   41,   41,   41,
       41,   41,   41,   41,   41,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,   46,   49,   49,   62,   62,
       49,   49,   49,   49,   49,   49,   49,   51,   51,   51,
       57,   57,   57,   61,   62,   61,   61,   61,   61,   61,
       63,   62,   62,   62,   63,   63,   63,   63,   63,   63,
       63,   64,   64,   64,  120,  120,   62,  120,  120,   62,

      120,  120,  120,  120,  120,  123,  123,   62,  123,  123,
      123,  123,  123,  123,  123,  123,  124,   62,   62,  124,
      124,  124,  124,  130,   62,   62,   62,   62,   62,  130,
      130,  133,   62,   62,  133,  133,  133,  133,  134,  134,
       62,  134,  134,  134,  134,  134,  134,  134,  134,  135,
      135,  135,  136,   62,   62,  136,  136,  136,  136,  203,
      203,   62,  203,  205,   62,  205,  205,  205,  205,  205,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,

       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,  129,   62,   62,   62,  129,   50,  122,  121,   62,
       56,   50,  448,   47,   47,    7,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448
    } ;

static yyconst short int yy_chk[1077] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    9,   21,    9,    3,    4,    3,    4,   16,
       26,   16,   17,   17,   17,   17,  447,   27,   22,   23,
        3,    4,   13,   13,   66,   13,   13,   25,   24,   28,
       29,   21,   13,   21,   13,   30,   23,   21,   13,   22,
       65,   26,   27,   33,   66,   13,   26,   25,   23,   24,

       31,   28,   30,   24,   22,   25,   32,   25,   37,   28,
       48,   29,   48,   34,   25,   35,  446,   31,   38,   36,
       68,   31,   40,   32,   67,   37,   33,   32,   65,   33,
       34,   31,   71,   37,   35,   32,   35,   32,   36,   38,
       39,   37,   34,   68,   34,   35,   34,   35,   36,   34,
       35,   36,   40,   40,   36,   36,   70,   39,   67,   52,
       73,   39,   78,   71,   39,   39,   53,   69,   52,   52,
       75,   39,   52,   55,   72,   53,   53,   53,   53,   52,
       74,   76,   55,   55,   55,   60,   60,   60,   60,   69,
       70,   72,   77,   55,   73,   78,   72,   79,   82,   80,

       83,   76,   84,   74,   75,   52,   86,   52,   88,   85,
       90,   87,   91,   77,   89,   93,   94,   95,   96,   55,
      444,   55,   80,   82,   99,   83,   86,   79,   85,   82,
       82,   87,   97,   82,   98,   84,  442,   89,   88,  101,
      102,   90,  100,  103,  104,   91,  105,   91,   95,   94,
       93,  106,   96,   99,  107,  109,  108,   97,  111,  100,
      112,  104,   98,  105,  110,  100,  113,  114,  101,  102,
      100,  116,  106,  109,  100,  111,  103,  115,  117,  112,
      119,  118,  137,  111,  114,  125,  143,  107,  108,  109,
      139,  113,  153,  110,  125,  125,  113,  140,  125,  137,

      142,  144,  115,  439,  116,  125,  126,  126,  155,  141,
      126,  117,  118,  119,  127,  139,  153,  126,  147,  126,
      143,  142,  140,  127,  127,  127,  127,  128,  128,  128,
      128,  125,  154,  125,  141,  144,  145,  131,  146,  147,
      128,  150,  148,  126,  155,  126,  131,  131,  131,  132,
      132,  132,  158,  145,  151,  146,  159,  131,  149,  152,
      132,  156,  132,  148,  161,  160,  162,  154,  145,  165,
      157,  150,  168,  151,  163,  151,  167,  149,  152,  159,
      149,  151,  158,  131,  164,  131,  132,  149,  132,  161,
      149,  157,  149,  149,  163,  169,  170,  156,  160,  171,

      172,  167,  162,  165,  168,  164,  173,  174,  175,  179,
      177,  178,  169,  180,  182,  183,  181,  185,  184,  186,
      171,  187,  190,  188,  189,  192,  193,  194,  206,  172,
      170,  177,  178,  181,  173,  195,  175,  184,  174,  196,
      179,  199,  182,  183,  180,  189,  215,  194,  185,  187,
      188,  186,  190,  191,  197,  191,  191,  212,  210,  438,
      192,  193,  195,  208,  215,  201,  201,  196,  206,  201,
      191,  207,  213,  209,  199,  197,  201,  221,  201,  202,
      202,  202,  202,  219,  191,  220,  191,  204,  204,  204,
      214,  212,  202,  208,  207,  209,  218,  210,  204,  210,

      204,  222,  201,  223,  201,  224,  225,  214,  213,  226,
      221,  229,  228,  218,  230,  231,  220,  235,  232,  219,
      223,  233,  237,  236,  204,  240,  204,  225,  238,  242,
      243,  244,  247,  222,  249,  246,  253,  254,  235,  230,
      224,  257,  255,  259,  233,  240,  226,  228,  251,  260,
      231,  242,  229,  232,  236,  246,  238,  247,  237,  248,
      244,  248,  248,  252,  256,  251,  243,  258,  249,  257,
      253,  254,  255,  259,  267,  261,  264,  260,  268,  248,
      252,  256,  269,  270,  273,  274,  273,  273,  277,  278,
      283,  280,  258,  280,  280,  248,  261,  284,  285,  258,

      286,  264,  287,  269,  267,  288,  274,  289,  290,  291,
      303,  268,  296,  304,  270,  283,  292,  295,  297,  278,
      297,  297,  277,  298,  301,  284,  305,  289,  286,  306,
      291,  285,  308,  290,  292,  288,  287,  296,  295,  303,
      298,  307,  304,  307,  307,  301,  311,  305,  309,  310,
      292,  314,  306,  315,  317,  318,  322,  324,  321,  325,
      327,  326,  333,  342,  329,  347,  344,  308,  348,  309,
      332,  330,  310,  341,  437,  343,  325,  350,  345,  324,
      351,  311,  314,  321,  326,  315,  329,  344,  317,  322,
      318,  330,  343,  332,  346,  333,  341,  348,  342,  345,

      327,  347,  349,  352,  353,  350,  356,  351,  357,  358,
      361,  365,  366,  346,  367,  368,  370,  373,  374,  375,
      372,  349,  376,  381,  376,  376,  377,  382,  377,  377,
      384,  361,  387,  366,  356,  353,  352,  370,  373,  367,
      358,  357,  372,  388,  381,  378,  365,  378,  378,  389,
      390,  391,  375,  368,  394,  401,  397,  382,  374,  384,
      399,  402,  404,  405,  404,  404,  414,  387,  407,  417,
      419,  388,  391,  420,  389,  390,  397,  418,  423,  424,
      425,  399,  430,  405,  394,  407,  414,  432,  434,  435,
      440,  402,  401,  436,  417,  420,  441,  433,  418,  431,

      429,  425,  443,  445,  428,  419,  427,  426,  422,  421,
      416,  430,  424,  434,  423,  415,  413,  412,  432,  411,
      440,  436,  410,  443,  445,  409,  408,  406,  403,  435,
      400,  398,  396,  441,  449,  449,  449,  449,  449,  449,
      449,  449,  449,  449,  449,  450,  450,  450,  450,  450,
      450,  450,  450,  450,  450,  450,  451,  451,  395,  393,
      451,  451,  451,  451,  451,  451,  451,  452,  452,  452,
      453,  453,  453,  454,  392,  454,  454,  454,  454,  454,
      455,  386,  385,  383,  455,  455,  455,  455,  455,  455,
      455,  456,  456,  456,  457,  457,  380,  457,  457,  379,

      457,  457,  457,  457,  457,  458,  458,  371,  458,  458,
      458,  458,  458,  458,  458,  458,  459,  369,  364,  459,
      459,  459,  459,  460,  363,  362,  360,  359,  355,  460,
      460,  461,  354,  340,  461,  461,  461,  461,  462,  462,
      339,  462,  462,  462,  462,  462,  462,  462,  462,  463,
      463,  463,  464,  338,  337,  464,  464,  464,  464,  465,
      465,  336,  465,  466,  335,  466,  466,  466,  466,  466,
      334,  331,  328,  323,  320,  319,  316,  313,  312,  302,
      300,  299,  294,  293,  282,  281,  279,  276,  275,  272,
      271,  266,  265,  263,  262,  250,  245,  241,  239,  234,

      227,  217,  216,  211,  205,  200,  198,  176,  166,  138,
      135,  129,   92,   81,   61,   54,   49,   44,   43,   18,
       14,   11,    7,    6,    5,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448,  448,  448,  448,  448,
      448,  448,  448,  448,  448,  448
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "vlex.l"
#define INITIAL 0
/*
 * Copyright (c) Tony Bybell 2006
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 */
#line 11 "vlex.l"
        
/*
 * vlex.l
 * 06apr06ajb
 */

/*
 * $Id$
 * $Log$
 * Revision 1.2  2007/04/20 02:08:10  gtkwave
 * initial release
 *
 */

#define YY_INPUT(buf, result, max_size) \
   result = v_preproc(buf, max_size);

#include "vlex.h"

int my_yylineno = 0;

static int yywrap(void)
{
return(1);
}

static int v_preproc_initialized = 0;
char *v_preproc_name = NULL;


static int v_preproc(char *buf, int max_size)
{
int ch;

if(!v_preproc_initialized)
	{
	yyin = fopen(v_preproc_name, "rb");
	if(!yyin) return(0);
	v_preproc_initialized = 1;
	my_yylineno = 1;	
	}

ch = fgetc(yyin);
if(ch!=EOF)
	{
	buf[0] = ch;
	buf[1] = 0;
	return(1);
	}
	else
	{
	fclose(yyin); yyin = NULL;
	v_preproc_initialized = 0;
	return (0);
	}
}

#define CMNT 1

#define PREPROC 2

#line 823 "vlex.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ))
#ifdef __GNUC__
    __attribute__((__unused__))
#endif
;
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, yy_size_t ));
#endif

#ifdef YY_NEED_STRLEN
static yy_size_t yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, (size_t)yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, (size_t)max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 73 "vlex.l"

#line 980 "vlex.c"

#if defined(YY_USES_REJECT) && (defined(__GNUC__) || defined(lint))
	/* XXX: shut up `unused label' warning with %options yylineno */
	if (/*CONSTCOND*/0 && yy_full_match)
		goto find_rule;
#endif
	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while (/*CONSTCOND*/ 1 )	/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 449 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1026 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 74 "vlex.l"
{ BEGIN CMNT; return V_CMT; }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 75 "vlex.l"
{ return V_CMT; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 76 "vlex.l"
{ BEGIN INITIAL; return V_CMT; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 77 "vlex.l"
{ return V_CMT; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 78 "vlex.l"
{ return V_CMT; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 79 "vlex.l"
{ my_yylineno++; return V_CMT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 81 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 82 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 83 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 84 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 85 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 86 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 87 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 88 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 89 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 90 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 91 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 92 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 93 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 94 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 95 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 96 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 97 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 98 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 99 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 100 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 101 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 102 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 103 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 104 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 105 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 106 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 107 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 108 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 109 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 110 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 111 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 112 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 113 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 114 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 115 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 116 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 117 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 118 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 119 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 120 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 121 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 122 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 123 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 124 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 125 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 126 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 127 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 128 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 129 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 130 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 131 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 132 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 133 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 134 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 135 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 136 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 137 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 138 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 139 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 140 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 141 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 142 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 143 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 144 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 147 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 148 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 149 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 150 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 151 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 152 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 153 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 154 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 155 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 156 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 157 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 158 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 159 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 160 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 161 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 162 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 163 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 164 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 165 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 166 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 167 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 168 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 169 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 172 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 173 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 174 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 175 "vlex.l"
{ return V_KW; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 178 "vlex.l"
{ return V_MODULE; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 179 "vlex.l"
{ return V_MODULE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 180 "vlex.l"
{ return V_MODULE; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 182 "vlex.l"
{ return V_ENDMODULE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 183 "vlex.l"
{ return V_ENDMODULE; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 185 "vlex.l"
{ return V_PREPROC_WS; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 186 "vlex.l"
{ my_yylineno++; BEGIN INITIAL; return V_WS; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 188 "vlex.l"
{ 
							if(is_builtin_define (yytext+1, yyleng-1))
								{
								BEGIN PREPROC;
								return(V_PREPROC);
								}

							return(V_MACRO);
							}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 199 "vlex.l"
{ return V_ID; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 200 "vlex.l"
{ return V_FUNC; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 201 "vlex.l"
{ return V_ID; }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 202 "vlex.l"
{ return V_ID; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 203 "vlex.l"
{ return V_PORT; }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 204 "vlex.l"
{ return V_NUMBER; }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 205 "vlex.l"
{ return V_NUMBER; }
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 206 "vlex.l"
{ return V_NUMBER; }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 207 "vlex.l"
{ return V_NUMBER; }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 208 "vlex.l"
{ return V_NUMBER; }
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 209 "vlex.l"
{ return V_IGNORE; }
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 210 "vlex.l"
{ return V_WS; }
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 211 "vlex.l"
{ my_yylineno++; return V_WS; }
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 212 "vlex.l"
{ return V_CMT; }
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 213 "vlex.l"
{ return V_STRING; }
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 214 "vlex.l"
{ return V_IGNORE; } 
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 216 "vlex.l"
ECHO;
	YY_BREAK
#line 1706 "vlex.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMNT):
case YY_STATE_EOF(PREPROC):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 449 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 449 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 448);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
#include <unistd.h>
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	yy_size_t len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, yy_size_t len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
yy_size_t len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n, i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, yy_size_t n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
yy_size_t n;
#endif
	{
	register yy_size_t i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static yy_size_t yy_flex_strlen( yyconst char *s )
#else
static yy_size_t yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register yy_size_t n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 216 "vlex.l"

